random_seed: 42
offer_text_max_length: 256
similar_offers_k: 50
als_mode: weighted
als_factors: 128
als_iterations: 50
als_regularization: 0.01
als_alpha: 40.0
als_time_decay_tau_days: 90.0
topk_brand: 4000
topk_seed: 4000
target_candidates: 10000
max_candidates: 10000
t_pop_days: 30
catboost_loss: YetiRank
catboost_iterations: 500
catboost_depth: 8
catboost_learning_rate: 0.05
catboost_l2_leaf_reg: 3.0
calibration_method: platt_logreg_1d
reasons_top_k: 3
nan_policy: impute
text_model_name: deepvk/USER-base
text_batch_size: 64
